// <auto-generated />
using System;
using MecHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MecHub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260921174406_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MecHub.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cpf");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<int>("MecanicoId")
                        .HasColumnType("int")
                        .HasColumnName("mecanico_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MecanicoId");

                    b.ToTable("cliente");
                });

            modelBuilder.Entity("MecHub.Models.ItemOrdemServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrdemServicoId")
                        .HasColumnType("int")
                        .HasColumnName("ordem_servico_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("quantidade");

                    b.Property<int>("ServicoId")
                        .HasColumnType("int")
                        .HasColumnName("servico_id");

                    b.HasKey("Id");

                    b.HasIndex("OrdemServicoId");

                    b.HasIndex("ServicoId");

                    b.ToTable("item_ordem_servico");
                });

            modelBuilder.Entity("MecHub.Models.Mecanico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext")
                        .HasColumnName("telefone");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("mecanico");
                });

            modelBuilder.Entity("MecHub.Models.OrdemServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_fechamento");

                    b.Property<int>("MecanicoId")
                        .HasColumnType("int")
                        .HasColumnName("mecanico_id");

                    b.Property<int>("StatusOrdem")
                        .HasColumnType("int")
                        .HasColumnName("status_ordem");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("int")
                        .HasColumnName("veiculo_id");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MecanicoId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("ordem_servico");
                });

            modelBuilder.Entity("MecHub.Models.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descricao");

                    b.Property<int>("MecanicoId")
                        .HasColumnType("int")
                        .HasColumnName("mecanico_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("MecanicoId");

                    b.ToTable("servico");
                });

            modelBuilder.Entity("MecHub.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("IdGoogle")
                        .HasColumnType("longtext")
                        .HasColumnName("id_google");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ResetSenhaExpiraEm")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("reset_senha_expira_em");

                    b.Property<string>("ResetSenhaToken")
                        .HasColumnType("longtext")
                        .HasColumnName("reset_senha_token");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(355)
                        .HasColumnType("varchar(355)");

                    b.Property<int>("TipoLogin")
                        .HasColumnType("int")
                        .HasColumnName("tipo_login");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("MecHub.Models.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoFabricacao")
                        .HasColumnType("int")
                        .HasColumnName("ano_fabricacao");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cor");

                    b.Property<DateTime>("DataAtualizacaoStatus")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_atualizacao_status");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("marca");

                    b.Property<int>("MecanicoId")
                        .HasColumnType("int")
                        .HasColumnName("mecanico_id");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("modelo");

                    b.Property<string>("ObservacaoStatus")
                        .HasColumnType("longtext")
                        .HasColumnName("observacao_status");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("placa");

                    b.Property<int>("StatusAtual")
                        .HasColumnType("int")
                        .HasColumnName("status_veiculo");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MecanicoId");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("veiculo");
                });

            modelBuilder.Entity("MecHub.Models.Cliente", b =>
                {
                    b.HasOne("MecHub.Models.Mecanico", "Mecanico")
                        .WithMany()
                        .HasForeignKey("MecanicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mecanico");
                });

            modelBuilder.Entity("MecHub.Models.ItemOrdemServico", b =>
                {
                    b.HasOne("MecHub.Models.OrdemServico", "OrdemServico")
                        .WithMany("Itens")
                        .HasForeignKey("OrdemServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MecHub.Models.Servico", "Servico")
                        .WithMany("Itens")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdemServico");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("MecHub.Models.Mecanico", b =>
                {
                    b.HasOne("MecHub.Models.Usuario", "Usuario")
                        .WithOne("Mecanico")
                        .HasForeignKey("MecHub.Models.Mecanico", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MecHub.Models.OrdemServico", b =>
                {
                    b.HasOne("MecHub.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MecHub.Models.Mecanico", "Mecanico")
                        .WithMany("OrdensServico")
                        .HasForeignKey("MecanicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MecHub.Models.Veiculo", "Veiculo")
                        .WithMany("OrdensServico")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Mecanico");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("MecHub.Models.Servico", b =>
                {
                    b.HasOne("MecHub.Models.Mecanico", "Mecanico")
                        .WithMany()
                        .HasForeignKey("MecanicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mecanico");
                });

            modelBuilder.Entity("MecHub.Models.Veiculo", b =>
                {
                    b.HasOne("MecHub.Models.Cliente", "Cliente")
                        .WithMany("Veiculos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MecHub.Models.Mecanico", "Mecanico")
                        .WithMany()
                        .HasForeignKey("MecanicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Mecanico");
                });

            modelBuilder.Entity("MecHub.Models.Cliente", b =>
                {
                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("MecHub.Models.Mecanico", b =>
                {
                    b.Navigation("OrdensServico");
                });

            modelBuilder.Entity("MecHub.Models.OrdemServico", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("MecHub.Models.Servico", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("MecHub.Models.Usuario", b =>
                {
                    b.Navigation("Mecanico");
                });

            modelBuilder.Entity("MecHub.Models.Veiculo", b =>
                {
                    b.Navigation("OrdensServico");
                });
#pragma warning restore 612, 618
        }
    }
}
